apt upgradable, desktop pc configs

diff --git a/polybar/shapes/scripts/checkupdates b/polybar/shapes/scripts/checkupdates
--- a/polybar/shapes/scripts/checkupdates
+++ b/polybar/shapes/scripts/checkupdates
@@ -99,18 +99,20 @@ fi
 
 trap 'rm -f $CHECKUPDATES_DB/db.lck' INT TERM EXIT
 
-DBPath="$(pacman-conf DBPath)"
+DBPath="$(apt-config DBPath)"
 if [[ -z "$DBPath" ]] || [[ ! -d "$DBPath" ]]; then
-	DBPath="/var/lib/pacman/"
+	DBPath="/var/lib/apt/"
 fi
 
-mkdir -p "$CHECKUPDATES_DB"
-ln -s "${DBPath}/local" "$CHECKUPDATES_DB" &> /dev/null
-if ! fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
-       error 'Cannot fetch updates'
-       exit 1
-fi
-pacman -Qu --dbpath "$CHECKUPDATES_DB" 2> /dev/null | grep -v '\[.*\]'
+#mkdir -p "$CHECKUPDATES_DB"
+#ln -s "${DBPath}/local" "$CHECKUPDATES_DB" &> /dev/null
+#if ! fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
+#       error 'Cannot fetch updates'
+#       exit 1
+#fi
+#pacman -Qu --dbpath "$CHECKUPDATES_DB" 2> /dev/null | grep -v '\[.*\]'
+fakeroot -- apt update &> /dev/null
+apt list --upgradable | grep '\[*]'
 
 exit 0
 
